# workflow name 
name: Deploy To Github Pages 

# 当有 push 到仓库和外部触发的时候就运行 
on: repository_dispatch

# YUQUE_TOKEN 
# Github_SSH_PRIVATE_KEY 
jobs:
  deploy: 
    name: Deploy Hexo Public To Pages 
    runs-on: ubuntu-latest 
    env: 
      TZ: Asia/Shanghai 

    steps: 
    # check it to your workflow can access it 
    # from: https://github.com/actions/checkout 
    - name: Checkout Repository source branch 
      uses: actions/checkout@v2
      with:
        ref: source 
    # from: https://github.com/actions/setup-node 
    - name: Setup Node.js 12.x 
      uses: actions/setup-node@master 
      with: 
        node-version: "12.x" 
    - name: Setup Github SSH_PRIVATE_KEY
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name 'CatcherInSky'
        git config --global user.email '1530775669@qq.com'
    # from https://github.com/x-cold/yuque-hexo 
    - name: Setup Hexo Dependencies and Generate Public Files 
      env: 
        YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }} 
      run: | 
        npm install hexo-cli -g 
        npm install yuque-hexo -g 
        npm install 
        npm run start
    # from https://github.com/peaceiris/actions-gh-pages 
    # this method can not push .github because it is a hidden folder
    # - name: Deploy 
    #   uses: peaceiris/actions-gh-pages@v3
    #   with: 
    #     deploy_key: ${{ secrets.SSH_PRIVATE_KEY }} 
    #     external_repository: CatcherInSky/CatcherInSky.github.io 
    #     publish_branch: master 
    #     publish_dir: ./public 
    #     commit_message: ${{ github.event.head_commit.message }}

# 参考资料：
# https://blog.csdn.net/z_johnny/article/details/103910373
# https://www.zhwei.cn/hexo-github-actions-yuque/#toc-heading-14
